- name: Installing nodejs and npm packages
  tags:
    - node
  block:
    - name: Install n
      community.general.homebrew:
        name: n
        state: latest

    - name: Install LTS version of Node.js using n
      ansible.builtin.command:
        cmd: n lts
      register: n_lts_result
      changed_when: true

    - name: Install npm packages globally
      ansible.builtin.command:
        cmd: npm install -g {{ item.name }}
      loop: "{{ node_npm_packages }}"
      register: npm_install_result
      changed_when: true
