homebrew_taps:
  - hashicorp/tap
homebrew_cask_packages:
  - name: google-cloud-sdk
  - name: google-chrome
  - name: clipy
    become: true
  - name: docker
  - name: miniconda
    become: true
  - name: adguard
  - name: obsidian
  - name: chatgpt
  - name: pycharm
homebrew_packages:
  - name: ansible
  - name: ansible-lint
  - name: speedtest-cli
  - name: battery
  - name: n
  - name: terraform
  - name: gh
  - name: git-flow
  - name: git-lfs
  - name: pre-commit
  - name: tox
  - name: ruff
  - name: docker-buildx
  - name: wget
  - name: gemini-cli
