homebrew_taps:
  - hashicorp/tap
  - terraform-linters/tap
homebrew_packages:
  - name: ansible
  - name: ansible-lint
  - name: speedtest-cli
  - name: uv
  - name: terraform
  - name: gh
  - name: git-lfs
  - name: pre-commit
  - name: ruff
  - name: libomp # Required by LightGBM (OpenMP runtime)
  - name: docker-buildx
  - name: wget
  - name: mas
  - name: ripgrep
homebrew_cask_packages:
  - name: terraform-linters/tap/tflint
  - name: google-cloud-sdk
  - name: google-chrome
  - name: clipy
    become: true
  - name: docker
  - name: miniconda
    become: true
  - name: adguard
  - name: pycharm
  - name: font-udev-gothic-nf
  - name: zotero
