name: Ansible CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test-playbook:
    name: Test Ansible Playbook
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        # Speeds up later job runs by restoring downloaded packages from a cache.
        # The cache is identified by the runner's OS and the hash of the requirements.txt file.
        # This means the cache is only rebuilt when the dependencies in requirements.txt change.
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Ansible
        run: pip3 install -r requirements.txt

      - name: Run Ansible Playbook Checks
        run: |
          echo "--- Running syntax-check ---"
          ansible-playbook localhost.yml -i inventory/localhost --syntax-check

          echo "--- Running dry-run ---"
          ansible-playbook localhost.yml -i inventory/localhost --check --extra-vars "git_user=test git_mail=test@test.com"
